"""
codegen.py — Playwright Test Code Generator
============================================
Converts QAPAL JSON test plans into standalone pytest-playwright .py files.
No QAPAL dependency at runtime — pure pytest + playwright.
"""

import json
import re
from pathlib import Path
from typing import Dict, List, Optional

from _log import get_logger

log = get_logger("codegen")

_HEADER = '''\
"""Auto-generated by QAPAL — https://github.com/ahmadsharabati/QAPAL"""
import re

from playwright.sync_api import Page, expect
'''


# ── Selector translation ─────────────────────────────────────────────

def _escape(s: str) -> str:
    """Escape a string for use inside Python string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _selector_to_code(sel: dict) -> str:
    """Convert a QAPAL selector dict to a Playwright locator expression."""
    strategy = sel.get("strategy", "")
    value = sel.get("value", "")

    if strategy == "testid":
        return f'page.get_by_test_id("{_escape(value)}")'

    if strategy == "role":
        if isinstance(value, dict):
            role = value.get("role", "")
            name = value.get("name", "")
            if name:
                return f'page.get_by_role("{_escape(role)}", name="{_escape(name)}")'
            return f'page.get_by_role("{_escape(role)}")'
        return f'page.get_by_role("{_escape(value)}")'

    if strategy == "role_container":
        if isinstance(value, dict):
            role = value.get("role", "")
            name = value.get("name", "")
            container = value.get("container", "")
            loc = f'page.get_by_role("{_escape(role)}"'
            if name:
                loc += f', name="{_escape(name)}"'
            loc += ")"
            if container:
                loc = f'page.locator("{_escape(container)}").get_by_role("{_escape(role)}"'
                if name:
                    loc += f', name="{_escape(name)}"'
                loc += ")"
            return loc
        return f'page.get_by_role("{_escape(value)}")'

    if strategy == "text":
        return f'page.get_by_text("{_escape(value)}")'

    if strategy == "label":
        return f'page.get_by_label("{_escape(value)}")'

    if strategy == "placeholder":
        return f'page.get_by_placeholder("{_escape(value)}")'

    if strategy == "alt_text":
        return f'page.get_by_alt_text("{_escape(value)}")'

    if strategy in ("aria-label", "aria_label"):
        return f"page.locator('[aria-label=\"{_escape(value)}\"]')"

    if strategy == "css":
        return f'page.locator("{_escape(value)}")'

    if strategy == "id":
        return f'page.locator("#{_escape(value)}")'

    if strategy == "testid_prefix":
        prefix = value
        index = sel.get("index", 0)
        return f"page.locator('[data-testid^=\"{_escape(prefix)}\"]').nth({index})"

    # Fallback: treat as CSS
    return f'page.locator("{_escape(str(value))}")'


# ── Action translation ────────────────────────────────────────────────

def _action_to_code(step: dict) -> List[str]:
    """Convert a QAPAL step dict to lines of Python code."""
    action = step.get("action", "")
    lines: List[str] = []

    if action == "navigate":
        url = _escape(step.get("url", ""))
        lines.append(f'page.goto("{url}", wait_until="domcontentloaded")')
        return lines

    if action == "refresh":
        lines.append("page.reload()")
        return lines

    if action == "go_back":
        lines.append("page.go_back()")
        return lines

    if action == "go_forward":
        lines.append("page.go_forward()")
        return lines

    if action == "scroll":
        dx = step.get("x", 0)
        dy = step.get("y", step.get("pixels", 500))
        lines.append(f"page.mouse.wheel({dx}, {dy})")
        return lines

    if action == "wait":
        sel = step.get("selector")
        duration = step.get("duration", step.get("value"))
        if sel:
            loc = _selector_to_code(sel)
            lines.append(f'{loc}.wait_for(state="visible")')
        elif duration:
            ms = int(float(duration) * 1000) if float(duration) < 100 else int(duration)
            lines.append(f"page.wait_for_timeout({ms})")
        else:
            lines.append("page.wait_for_timeout(1000)")
        return lines

    if action == "screenshot":
        label = step.get("label", step.get("name", "screenshot"))
        safe_label = re.sub(r"[^a-zA-Z0-9_-]", "_", label)
        lines.append(f'page.screenshot(path="screenshots/{safe_label}.png")')
        return lines

    if action == "evaluate":
        script = _escape(step.get("script", step.get("value", "")))
        lines.append(f'page.evaluate("{script}")')
        return lines

    # All remaining actions need a selector
    sel = step.get("selector")
    if not sel:
        lines.append(f"# WARNING: action '{action}' missing selector — skipped")
        return lines

    loc = _selector_to_code(sel)

    if action == "click":
        lines.append(f"{loc}.click()")
    elif action == "dblclick":
        lines.append(f"{loc}.dblclick()")
    elif action == "fill":
        val = _escape(step.get("value", ""))
        lines.append(f'{loc}.fill("{val}")')
    elif action == "type":
        val = _escape(step.get("value", step.get("text", "")))
        lines.append(f'{loc}.type("{val}")')
    elif action == "clear":
        lines.append(f"{loc}.clear()")
    elif action == "press":
        key = _escape(step.get("key", step.get("value", "Enter")))
        lines.append(f'{loc}.press("{key}")')
    elif action == "select":
        label = step.get("label", step.get("value", ""))
        lines.append(f'{loc}.select_option(label="{_escape(label)}")')
    elif action == "check":
        lines.append(f"{loc}.check()")
    elif action == "uncheck":
        lines.append(f"{loc}.uncheck()")
    elif action == "hover":
        lines.append(f"{loc}.hover()")
    elif action == "focus":
        lines.append(f"{loc}.focus()")
    elif action == "blur":
        lines.append(f"{loc}.blur()")
    else:
        lines.append(f"# WARNING: unknown action '{action}' — skipped")

    return lines


# ── Assertion translation ─────────────────────────────────────────────

def _assertion_to_code(a: dict) -> List[str]:
    """Convert a QAPAL assertion dict to lines of Python code."""
    atype = a.get("type", "")
    value = a.get("value", "")
    sel = a.get("selector")
    lines: List[str] = []

    # Page-level assertions
    if atype == "url_equals":
        lines.append(f'expect(page).to_have_url("{_escape(str(value))}")')
    elif atype == "url_contains":
        escaped = _escape(re.escape(str(value)))
        lines.append(f'expect(page).to_have_url(re.compile(r".*{escaped}.*"))')
    elif atype == "url_matches":
        lines.append(f'expect(page).to_have_url(re.compile(r"{_escape(str(value))}"))')
    elif atype == "title_equals":
        lines.append(f'expect(page).to_have_title("{_escape(str(value))}")')
    elif atype == "title_contains":
        escaped = _escape(re.escape(str(value)))
        lines.append(f'expect(page).to_have_title(re.compile(r".*{escaped}.*"))')

    # Element assertions (need selector)
    elif sel:
        loc = _selector_to_code(sel)
        if atype == "element_visible":
            lines.append(f"expect({loc}).to_be_visible()")
        elif atype == "element_hidden":
            lines.append(f"expect({loc}).to_be_hidden()")
        elif atype == "element_exists":
            lines.append(f"expect({loc}).to_be_attached()")
        elif atype == "element_enabled":
            lines.append(f"expect({loc}).to_be_enabled()")
        elif atype == "element_disabled":
            lines.append(f"expect({loc}).to_be_disabled()")
        elif atype == "element_checked":
            lines.append(f"expect({loc}).to_be_checked()")
        elif atype == "element_unchecked":
            lines.append(f"expect({loc}).not_to_be_checked()")
        elif atype == "element_focused":
            lines.append(f"expect({loc}).to_be_focused()")
        elif atype == "element_text_equals":
            lines.append(f'expect({loc}).to_have_text("{_escape(str(value))}")')
        elif atype in ("element_text_contains", "element_contains_text"):
            lines.append(f'expect({loc}).to_contain_text("{_escape(str(value))}")')
        elif atype == "element_value_equals":
            lines.append(f'expect({loc}).to_have_value("{_escape(str(value))}")')
        elif atype == "element_has_class":
            escaped = _escape(re.escape(str(value)))
            lines.append(f'expect({loc}).to_have_class(re.compile(r".*{escaped}.*"))')
        elif atype == "element_count":
            lines.append(f"expect({loc}).to_have_count({int(value)})")
        elif atype == "element_attribute":
            attr = a.get("attribute", a.get("attr", ""))
            lines.append(f'expect({loc}).to_have_attribute("{_escape(attr)}", "{_escape(str(value))}")')
        elif atype == "element_in_viewport":
            lines.append(f"expect({loc}).to_be_in_viewport()")
        else:
            lines.append(f"# WARNING: unknown assertion '{atype}' — skipped")
    else:
        lines.append(f"# WARNING: assertion '{atype}' missing selector — skipped")

    return lines


# ── Function naming ───────────────────────────────────────────────────

def _plan_to_function_name(plan: dict) -> str:
    """Convert a plan's test_id or name to a valid Python test function name."""
    raw = plan.get("test_id", "") or plan.get("name", "unnamed_test")
    # Lowercase, replace non-alphanumeric with underscore
    name = re.sub(r"[^a-z0-9]+", "_", raw.lower()).strip("_")
    if not name.startswith("test_"):
        name = "test_" + name
    return name


# ── Main code generator ──────────────────────────────────────────────

def generate_test_file(plan: dict) -> str:
    """Generate a standalone pytest-playwright test file from a QAPAL JSON plan."""
    func_name = _plan_to_function_name(plan)
    test_name = plan.get("name", plan.get("test_id", ""))
    steps = plan.get("steps", [])
    assertions = plan.get("assertions", [])

    lines: List[str] = []
    lines.append(_HEADER)
    lines.append("")
    lines.append(f"def {func_name}(page: Page):")
    if test_name:
        lines.append(f'    """{test_name}"""')

    if not steps and not assertions:
        lines.append("    pass")
        return "\n".join(lines) + "\n"

    # Steps
    for i, step in enumerate(steps, 1):
        action = step.get("action", "")
        comment = f"Step {i}: {action}"
        if action == "navigate":
            comment += f" to {step.get('url', '')}"
        elif step.get("selector"):
            sel = step["selector"]
            sv = sel.get("value", "")
            if isinstance(sv, dict):
                sv = sv.get("name", sv.get("role", ""))
            comment += f" ({sv})"

        lines.append(f"    # {comment}")
        code_lines = _action_to_code(step)
        for cl in code_lines:
            lines.append(f"    {cl}")
        lines.append("")

    # Assertions
    if assertions:
        lines.append("    # Assertions")
        for j, a in enumerate(assertions, 1):
            atype = a.get("type", "")
            lines.append(f"    # Assertion {j}: {atype}")
            code_lines = _assertion_to_code(a)
            for cl in code_lines:
                lines.append(f"    {cl}")

    return "\n".join(lines) + "\n"


def generate_test_file_multi(plans: List[dict]) -> str:
    """Generate a single test file containing multiple test functions."""
    func_bodies: List[str] = []
    for plan in plans:
        body = generate_test_file(plan)
        # Strip the header from all but the first
        if func_bodies:
            # Remove the header lines (everything before `def test_`)
            idx = body.find("\ndef test_")
            if idx == -1:
                idx = body.find("def test_")
            if idx >= 0:
                body = body[idx:].lstrip("\n")
        func_bodies.append(body)

    return "\n\n".join(func_bodies) + "\n"


# ── File I/O helpers ──────────────────────────────────────────────────

def codegen_plan_file(plan_path: str, output_dir: str = "tests/generated") -> str:
    """Read a plan JSON, generate a .py file, write it to output_dir. Returns output path."""
    with open(plan_path, "r") as f:
        plan = json.load(f)

    code = generate_test_file(plan)

    # Validate generated code compiles
    try:
        compile(code, "<codegen>", "exec")
    except SyntaxError as e:
        log.warning("Generated code has syntax error: %s", e)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    plan_name = Path(plan_path).stem
    safe_name = re.sub(r"[^a-z0-9_]", "_", plan_name.lower())
    if not safe_name.startswith("test_"):
        safe_name = "test_" + safe_name
    out_path = out_dir / f"{safe_name}.py"

    out_path.write_text(code, encoding="utf-8")
    log.info("  [codegen] %s → %s", plan_path, out_path)
    return str(out_path)


def codegen_plans(plan_paths: List[str], output_dir: str = "tests/generated") -> List[str]:
    """Generate .py files for multiple plans. Returns list of output paths."""
    results = []
    for p in plan_paths:
        try:
            out = codegen_plan_file(p, output_dir)
            results.append(out)
        except Exception as e:
            log.error("  [codegen] Failed on %s: %s", p, e)
    return results
